# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X343kn2ozaR3h2lYElVkbIdl4EKD9QVA
"""

!pip install simpy

import simpy
import random
import numpy as np

#Parametros do meu sistema
TAXA_CHEGADA = 0.5
TAXA_SERVICO = 1.0
NUM_SERVIDORES = 1
TEMPO_SIMULACAO = 10
tempo_de_espera = []

# Função que gerencia as chegadas dos clientes no sistema
def cliente(env, nome, servidor):
  chegada = env.now

  print(f'{nome} chegou em {chegada:.2f}')

  with servidor.request() as req:
    yield req #Espera ser atendido
    inicio_servico = env.now

    tempo_de_espera.append(inicio_servico - chegada)

    print(f'{nome} começou o atendimento em {inicio_servico:.2f}')
    #tempo de atendimento
    tempo_atendimento = random.expovariate(TAXA_SERVICO)

    yield env.timeout(tempo_atendimento)

    fim_servico = env.now
    print(f'{nome} terminou o atendimento em {fim_servico:.2f}')

#Gera as chegadas dos clientes
def gerar_clientes(env, servidor):
  contador = 0
  while True:
    yield env.timeout(random.expovariate(TAXA_CHEGADA))
    contador += 1
    env.process(cliente(env, f'Cliente {contador}', servidor))


def simular():
  env = simpy.Environment()
  servidor = simpy.Resource(env, capacity = NUM_SERVIDORES)
  #INICIAR O PROCESSO DE GERAÇÃO DE CLIENTES
  env.process(gerar_clientes(env, servidor))
  env.run(until = TEMPO_SIMULACAO)

  print(f'Tempo médio de espera (W) : {np.mean(tempo_de_espera)}')
  print(f'Variancia do tempo médio de espera (W) : {np.var(tempo_de_espera)}')

simular()

