/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Acertos;

/**
 *
 * @author pedrohenrique.clima
 */
public class Tela extends javax.swing.JFrame {
    Acertos a = new Acertos();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRQ1opcao1 = new javax.swing.JRadioButton();
        jRQ1opcao2 = new javax.swing.JRadioButton();
        jRQ1opcao5 = new javax.swing.JRadioButton();
        jRQ1opcao3 = new javax.swing.JRadioButton();
        jRQ1opcao4 = new javax.swing.JRadioButton();
        jBescolher = new javax.swing.JButton();
        jLresultado1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLtotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBescolher1 = new javax.swing.JButton();
        jRQ2opcao1 = new javax.swing.JRadioButton();
        jRQ2opcao2 = new javax.swing.JRadioButton();
        jRQ2opcao5 = new javax.swing.JRadioButton();
        jRQ2opcao3 = new javax.swing.JRadioButton();
        jRQ2opcao4 = new javax.swing.JRadioButton();
        jLresultado2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRQ4opcao2 = new javax.swing.JRadioButton();
        jBescolher3 = new javax.swing.JButton();
        jRQ4opcao4 = new javax.swing.JRadioButton();
        jRQ4opcao3 = new javax.swing.JRadioButton();
        jRQ4opcao1 = new javax.swing.JRadioButton();
        jRQ4opcao5 = new javax.swing.JRadioButton();
        jLresultado4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRQ5opcao4 = new javax.swing.JRadioButton();
        jRQ5opcao3 = new javax.swing.JRadioButton();
        jBescolher4 = new javax.swing.JButton();
        jRQ5opcao1 = new javax.swing.JRadioButton();
        jRQ5opcao2 = new javax.swing.JRadioButton();
        jRQ5opcao5 = new javax.swing.JRadioButton();
        jLresultado5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBescolher2 = new javax.swing.JButton();
        jRQ3opcao2 = new javax.swing.JRadioButton();
        jRQ3opcao4 = new javax.swing.JRadioButton();
        jRQ3opcao5 = new javax.swing.JRadioButton();
        jRQ3opcao3 = new javax.swing.JRadioButton();
        jRQ3opcao1 = new javax.swing.JRadioButton();
        jLresultado3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Questão 1: Qual é o maior planeta do sistema solar?");

        buttonGroup1.add(jRQ1opcao1);
        jRQ1opcao1.setText("Terra");

        buttonGroup1.add(jRQ1opcao2);
        jRQ1opcao2.setText("Marte");

        buttonGroup1.add(jRQ1opcao5);
        jRQ1opcao5.setText("netuno");
        jRQ1opcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ1opcao5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRQ1opcao3);
        jRQ1opcao3.setText("Júpiter");

        buttonGroup1.add(jRQ1opcao4);
        jRQ1opcao4.setText("Saturno");
        jRQ1opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ1opcao4ActionPerformed(evt);
            }
        });

        jBescolher.setText("Escolha");
        jBescolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBescolherActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("ACERTOS:");

        jLtotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLtotal.setText("0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLtotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jRQ1opcao1)
                        .addGap(37, 37, 37)
                        .addComponent(jRQ1opcao2)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBescolher)
                                .addGap(30, 30, 30)
                                .addComponent(jLresultado1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRQ1opcao3)
                                .addGap(18, 18, 18)
                                .addComponent(jRQ1opcao4)
                                .addGap(18, 18, 18)
                                .addComponent(jRQ1opcao5)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLtotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRQ1opcao5)
                    .addComponent(jRQ1opcao4)
                    .addComponent(jRQ1opcao3)
                    .addComponent(jRQ1opcao2)
                    .addComponent(jRQ1opcao1))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolher)
                    .addComponent(jLresultado1))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Questão 2: Quem escreveu \"Dom Casmurro\"?");

        jBescolher1.setText("Escolha");
        jBescolher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBescolher1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRQ2opcao1);
        jRQ2opcao1.setText("Jorge Amado");

        buttonGroup2.add(jRQ2opcao2);
        jRQ2opcao2.setText("Manuel Bandeira");

        buttonGroup2.add(jRQ2opcao5);
        jRQ2opcao5.setText("Érico Veríssimo");
        jRQ2opcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ2opcao5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRQ2opcao3);
        jRQ2opcao3.setText("Machado de Assis");

        buttonGroup2.add(jRQ2opcao4);
        jRQ2opcao4.setText("Clarice Lispector");
        jRQ2opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ2opcao4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRQ2opcao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRQ2opcao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBescolher1)
                                .addGap(26, 26, 26)
                                .addComponent(jLresultado2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRQ2opcao3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRQ2opcao4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRQ2opcao5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRQ2opcao1)
                    .addComponent(jRQ2opcao2)
                    .addComponent(jRQ2opcao3)
                    .addComponent(jRQ2opcao4)
                    .addComponent(jRQ2opcao5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolher1)
                    .addComponent(jLresultado2))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Questão 4: Qual elemento químico tem o símbolo \"O\"?");

        buttonGroup4.add(jRQ4opcao2);
        jRQ4opcao2.setText("Oxigênio");

        jBescolher3.setText("Escolha");
        jBescolher3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBescolher3ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRQ4opcao4);
        jRQ4opcao4.setText("Óxido");
        jRQ4opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ4opcao4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRQ4opcao3);
        jRQ4opcao3.setText("Ósmio");

        buttonGroup4.add(jRQ4opcao1);
        jRQ4opcao1.setText("Ouro");

        buttonGroup4.add(jRQ4opcao5);
        jRQ4opcao5.setText("Hidrogênio");
        jRQ4opcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ4opcao5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRQ4opcao1)
                        .addGap(47, 47, 47)
                        .addComponent(jRQ4opcao2)
                        .addGap(59, 59, 59)
                        .addComponent(jRQ4opcao3)
                        .addGap(18, 18, 18)
                        .addComponent(jRQ4opcao4)
                        .addGap(18, 18, 18)
                        .addComponent(jRQ4opcao5)
                        .addGap(179, 179, 179))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(jLresultado4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(jBescolher3)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRQ4opcao1)
                    .addComponent(jRQ4opcao2)
                    .addComponent(jRQ4opcao3)
                    .addComponent(jRQ4opcao4)
                    .addComponent(jRQ4opcao5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolher3)
                    .addComponent(jLresultado4))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Questão 5: Em que ano o homem pisou na Lua pela primeira vez?");

        buttonGroup5.add(jRQ5opcao4);
        jRQ5opcao4.setText("1975");
        jRQ5opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ5opcao4ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRQ5opcao3);
        jRQ5opcao3.setText("1971");

        jBescolher4.setText("Escolha");
        jBescolher4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBescolher4ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRQ5opcao1);
        jRQ5opcao1.setText("1965");

        buttonGroup5.add(jRQ5opcao2);
        jRQ5opcao2.setText("1969");

        buttonGroup5.add(jRQ5opcao5);
        jRQ5opcao5.setText("1980");
        jRQ5opcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ5opcao5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jRQ5opcao1)
                                .addGap(44, 44, 44)
                                .addComponent(jRQ5opcao2))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLresultado5)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBescolher4)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jRQ5opcao3)
                                .addGap(40, 40, 40)
                                .addComponent(jRQ5opcao4)
                                .addGap(50, 50, 50)
                                .addComponent(jRQ5opcao5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRQ5opcao3)
                    .addComponent(jRQ5opcao2)
                    .addComponent(jRQ5opcao1)
                    .addComponent(jRQ5opcao4)
                    .addComponent(jRQ5opcao5))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLresultado5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBescolher4)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Questão 3: Qual é a capital da França?");

        jBescolher2.setText("Escolha");
        jBescolher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBescolher2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRQ3opcao2);
        jRQ3opcao2.setText("Roma");

        buttonGroup3.add(jRQ3opcao4);
        jRQ3opcao4.setText("Paris");
        jRQ3opcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ3opcao4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRQ3opcao5);
        jRQ3opcao5.setText("Lisboa");
        jRQ3opcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRQ3opcao5ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRQ3opcao3);
        jRQ3opcao3.setText("Berlim");

        buttonGroup3.add(jRQ3opcao1);
        jRQ3opcao1.setText("Madri");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jRQ3opcao1)
                        .addGap(58, 58, 58)
                        .addComponent(jRQ3opcao2)
                        .addGap(42, 42, 42)
                        .addComponent(jRQ3opcao3)
                        .addGap(41, 41, 41)
                        .addComponent(jRQ3opcao4)
                        .addGap(42, 42, 42)
                        .addComponent(jRQ3opcao5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jBescolher2)
                        .addGap(18, 18, 18)
                        .addComponent(jLresultado3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRQ3opcao1)
                    .addComponent(jRQ3opcao2)
                    .addComponent(jRQ3opcao3)
                    .addComponent(jRQ3opcao4)
                    .addComponent(jRQ3opcao5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolher2)
                    .addComponent(jLresultado3))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRQ1opcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ1opcao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ1opcao5ActionPerformed

    private void jRQ1opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ1opcao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ1opcao4ActionPerformed

    private void jRQ2opcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ2opcao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ2opcao5ActionPerformed

    private void jRQ2opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ2opcao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ2opcao4ActionPerformed

    private void jRQ3opcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ3opcao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ3opcao5ActionPerformed

    private void jRQ3opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ3opcao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ3opcao4ActionPerformed

    private void jRQ4opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ4opcao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ4opcao4ActionPerformed

    private void jRQ4opcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ4opcao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ4opcao5ActionPerformed

    private void jRQ5opcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ5opcao4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ5opcao4ActionPerformed

    private void jRQ5opcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRQ5opcao5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRQ5opcao5ActionPerformed

    private void jBescolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBescolherActionPerformed
        // TODO add your handling code here:
        if(jRQ1opcao1.isSelected()){
            jLresultado1.setText("Errou!");
        } else if (jRQ1opcao2.isSelected()){
            jLresultado1.setText("Errou!");
        } else if (jRQ1opcao3.isSelected()){
            jLresultado1.setText("ACERTOU");
        } else if (jRQ1opcao4.isSelected()){
            jLresultado1.setText("Errou!");
        } else if (jRQ1opcao5.isSelected()){
            jLresultado1.setText("Errou!");
        } else {
            jLresultado1.setText("Selecione uma alternativa!");
        }
        jLtotal.setText(":"+ a.somar());
    }//GEN-LAST:event_jBescolherActionPerformed

    private void jBescolher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBescolher1ActionPerformed
        // TODO add your handling code here:
        if(jRQ2opcao1.isSelected()){
            jLresultado2.setText("Errou!");
        } else if (jRQ2opcao2.isSelected()){
            jLresultado2.setText("Errou!");
        } else if (jRQ2opcao3.isSelected()){
            jLresultado2.setText("ACERTOU");
        } else if (jRQ2opcao4.isSelected()){
            jLresultado2.setText("Errou!");
        } else if (jRQ2opcao5.isSelected()){
            jLresultado2.setText("Errou!");
        } else {
            jLresultado2.setText("Selecione uma alternativa!");
        }
    }//GEN-LAST:event_jBescolher1ActionPerformed

    private void jBescolher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBescolher2ActionPerformed
        // TODO add your handling code here:
        if(jRQ3opcao1.isSelected()){
            jLresultado3.setText("Errou!");
        } else if (jRQ3opcao2.isSelected()){
            jLresultado3.setText("Errou!");
        } else if (jRQ3opcao3.isSelected()){
            jLresultado3.setText("Errou");
        } else if (jRQ3opcao4.isSelected()){
            jLresultado3.setText("ACERTOU!");
        } else if (jRQ3opcao5.isSelected()){
            jLresultado3.setText("Errou!");
        } else {
            jLresultado3.setText("Selecione uma alternativa!");
        }
    }//GEN-LAST:event_jBescolher2ActionPerformed

    private void jBescolher3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBescolher3ActionPerformed
        // TODO add your handling code here:
        if(jRQ4opcao1.isSelected()){
            jLresultado4.setText("Errou!");
        } else if (jRQ4opcao2.isSelected()){
            jLresultado4.setText("ACERTOU!");
        } else if (jRQ4opcao3.isSelected()){
            jLresultado4.setText("Errou!");
        } else if (jRQ4opcao4.isSelected()){
            jLresultado4.setText("Errou!");
        } else if (jRQ4opcao5.isSelected()){
            jLresultado4.setText("Errou!");
        } else {
            jLresultado4.setText("Selecione uma alternativa!");
        }
    }//GEN-LAST:event_jBescolher3ActionPerformed

    private void jBescolher4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBescolher4ActionPerformed
        // TODO add your handling code here:
        if(jRQ5opcao1.isSelected()){
            jLresultado5.setText("Errou!");
        } else if (jRQ5opcao2.isSelected()){
            jLresultado5.setText("ACERTOU!");
        } else if (jRQ5opcao3.isSelected()){
            jLresultado5.setText("Errou!");
        } else if (jRQ5opcao4.isSelected()){
            jLresultado5.setText("Errou!");
        } else if (jRQ5opcao5.isSelected()){
            jLresultado5.setText("Errou!");
        } else {
            jLresultado5.setText("Selecione uma alternativa!");
        }
    }//GEN-LAST:event_jBescolher4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jBescolher;
    private javax.swing.JButton jBescolher1;
    private javax.swing.JButton jBescolher2;
    private javax.swing.JButton jBescolher3;
    private javax.swing.JButton jBescolher4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLresultado1;
    private javax.swing.JLabel jLresultado2;
    private javax.swing.JLabel jLresultado3;
    private javax.swing.JLabel jLresultado4;
    private javax.swing.JLabel jLresultado5;
    private javax.swing.JLabel jLtotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRQ1opcao1;
    private javax.swing.JRadioButton jRQ1opcao2;
    private javax.swing.JRadioButton jRQ1opcao3;
    private javax.swing.JRadioButton jRQ1opcao4;
    private javax.swing.JRadioButton jRQ1opcao5;
    private javax.swing.JRadioButton jRQ2opcao1;
    private javax.swing.JRadioButton jRQ2opcao2;
    private javax.swing.JRadioButton jRQ2opcao3;
    private javax.swing.JRadioButton jRQ2opcao4;
    private javax.swing.JRadioButton jRQ2opcao5;
    private javax.swing.JRadioButton jRQ3opcao1;
    private javax.swing.JRadioButton jRQ3opcao2;
    private javax.swing.JRadioButton jRQ3opcao3;
    private javax.swing.JRadioButton jRQ3opcao4;
    private javax.swing.JRadioButton jRQ3opcao5;
    private javax.swing.JRadioButton jRQ4opcao1;
    private javax.swing.JRadioButton jRQ4opcao2;
    private javax.swing.JRadioButton jRQ4opcao3;
    private javax.swing.JRadioButton jRQ4opcao4;
    private javax.swing.JRadioButton jRQ4opcao5;
    private javax.swing.JRadioButton jRQ5opcao1;
    private javax.swing.JRadioButton jRQ5opcao2;
    private javax.swing.JRadioButton jRQ5opcao3;
    private javax.swing.JRadioButton jRQ5opcao4;
    private javax.swing.JRadioButton jRQ5opcao5;
    // End of variables declaration//GEN-END:variables
}
