/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Dividir;
import br.com.controle.Media;
import br.com.controle.Multiplicar;
import br.com.controle.OperacaoMatematica;
import br.com.controle.Soma;
import br.com.controle.Subtracao;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrohenrique.clima
 */
public class Tela extends javax.swing.JFrame {
    public static double calcule(OperacaoMatematica op, double valor1, double valor2){
        return op.calcular(valor1, valor2);
    }
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jTvalor2 = new javax.swing.JTextField();
        jBSubtrair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLResultado = new javax.swing.JLabel();
        jBSomar1 = new javax.swing.JButton();
        jBDIvidir = new javax.swing.JButton();
        jBMultiplicar = new javax.swing.JButton();
        jBMedia1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CALCULADORA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Valor 2:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Valor 1:");

        jTvalor1.setColumns(4);

        jTvalor2.setColumns(4);

        jBSubtrair.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBSubtrair.setText("-");
        jBSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubtrairActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Resultado:");

        jLResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLResultado.setText("0.00");

        jBSomar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBSomar1.setText("+");
        jBSomar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomar1ActionPerformed(evt);
            }
        });

        jBDIvidir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBDIvidir.setText("/");
        jBDIvidir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDIvidirActionPerformed(evt);
            }
        });

        jBMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBMultiplicar.setText("*");
        jBMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicarActionPerformed(evt);
            }
        });

        jBMedia1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBMedia1.setText("Média");
        jBMedia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMedia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(33, 33, 33)
                                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLResultado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jBSomar1)
                                .addGap(33, 33, 33)
                                .addComponent(jBSubtrair)
                                .addGap(36, 36, 36)
                                .addComponent(jBMultiplicar)
                                .addGap(41, 41, 41)
                                .addComponent(jBDIvidir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jBMedia1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSubtrair)
                    .addComponent(jBDIvidir)
                    .addComponent(jBMultiplicar)
                    .addComponent(jBSomar1)
                    .addComponent(jBMedia1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLResultado))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubtrairActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor1.requestFocus();
        } else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTvalor1.getText());
            double pvalor2 = Double.valueOf(jTvalor2.getText());
            jLResultado.setText(String.valueOf(calcule(new Subtracao(), pvalor1, pvalor2)));
        }
    }//GEN-LAST:event_jBSubtrairActionPerformed

    private void jBSomar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomar1ActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor1.requestFocus();
        } else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTvalor1.getText());
            double pvalor2 = Double.valueOf(jTvalor2.getText());
            jLResultado.setText(String.valueOf(calcule(new Soma(), pvalor1, pvalor2)));
        }
    }//GEN-LAST:event_jBSomar1ActionPerformed

    private void jBDIvidirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDIvidirActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor1.requestFocus();
        } else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTvalor1.getText());
            double pvalor2 = Double.valueOf(jTvalor2.getText());
            jLResultado.setText(String.valueOf(calcule(new Dividir(), pvalor1, pvalor2)));
        }
    }//GEN-LAST:event_jBDIvidirActionPerformed

    private void jBMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicarActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor1.requestFocus();
        } else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTvalor1.getText());
            double pvalor2 = Double.valueOf(jTvalor2.getText());
            jLResultado.setText(String.valueOf(calcule(new Multiplicar(), pvalor1, pvalor2)));
        }
    }//GEN-LAST:event_jBMultiplicarActionPerformed

    private void jBMedia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMedia1ActionPerformed
        // TODO add your handling code here:
        if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor1.requestFocus();
        } else if(jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo obrigatório");
            jTvalor2.requestFocus();
        } else {
            double pvalor1 = Double.valueOf(jTvalor1.getText());
            double pvalor2 = Double.valueOf(jTvalor2.getText());
            jLResultado.setText(String.valueOf(calcule(new Media(), pvalor1, pvalor2)));
        }
    }//GEN-LAST:event_jBMedia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDIvidir;
    private javax.swing.JButton jBMedia1;
    private javax.swing.JButton jBMultiplicar;
    private javax.swing.JButton jBSomar1;
    private javax.swing.JButton jBSubtrair;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    // End of variables declaration//GEN-END:variables
}
